<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Simulation Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Simulation Challenge</h1>
<p class="subtitle lead">Starter Template with To-Dos</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>:::</p>
<section id="the-investment-game-brief" class="level2">
<h2 class="anchored" data-anchor-id="the-investment-game-brief">The Investment Game (Brief)</h2>
<p>You have the opportunity to buy-in to this game next week with $30,000. Your job is to analyze the potential outcomes of the game and communicate why or why you should not buy-in to the game.</p>
<p>Each year after buy-in you flip a fair coin:</p>
<ul>
<li>Heads: increase your account balance by 50%</li>
<li>Tails: decrease your account balance by 40%</li>
</ul>
<p>You play annually until age 75. Your mission is to analyze outcomes and communicate insights clearly.</p>
<section id="generative-dag-model-from-the-source-challenge" class="level3">
<h3 class="anchored" data-anchor-id="generative-dag-model-from-the-source-challenge">Generative DAG Model (from the source challenge)</h3>
<p>The following DAFT diagram shows the generative structure of the investment game over time.</p>
<div id="cell-fig-investment-dag" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-investment-dag" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-investment-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-investment-dag-output-1.png" width="649" height="220" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-investment-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Generative DAG model for the investment game showing how wealth evolves over time through coin flips
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="expected-value-after-1-flip" class="level3">
<h3 class="anchored" data-anchor-id="expected-value-after-1-flip">1) Expected Value After 1 Flip</h3>
<p>After one flip, the expected value of your account balance is <strong>greater than</strong> $30,000. The calculation shows that with a fair coin flip (50% probability for each outcome), you have a 50% chance of ending up with $45,000 (heads: +50%) and a 50% chance of ending up with $18,000 (tails: -40%). The expected value is $31,500, which represents a <strong>gain of $1,500 or 5%</strong> above your initial buy-in.</p>
<p>Based on expected value alone, this simple analysis suggests you should buy-in to the game, as it offers a positive expected return. However, this single-metric analysis overlooks the substantial risk: you have a 50% chance of losing $12,000 (40% of your investment) in just one flip. This highlights the importance of considering both expected value and risk when making investment decisions, especially when multiple periods are involved.</p>
<div id="q1-expected-value-py" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Initial balance: $30,000.00

After one flip:
  Heads (50% probability): $45,000.00
  Tails (50% probability): $18,000.00

Expected Value (EV) after one flip:
  EV = 0.5 × $45,000.00 + 0.5 × $18,000.00
  EV = $31,500.00

Comparison to initial balance:
  EV - Initial = $1,500.00
  Gain as % of buy-in: 5.00%

Conclusion:
  Expected value ($31,500.00) &gt; Initial balance ($30,000.00)
  The expected value suggests a positive return of 5.00%</code></pre>
</div>
</div>
</section>
<section id="single-simulation-over-time-narrative-plot" class="level3">
<h3 class="anchored" data-anchor-id="single-simulation-over-time-narrative-plot">2) Single Simulation Over Time (Narrative + Plot)</h3>
<div id="cell-q2-single-sim-py" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="q2-single-sim-py" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/q2-single-sim-py-output-1.png" width="759" height="566" class="figure-img"></p>
<figcaption>Single simulation path of account balance over time</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Simulation Summary:
  Initial balance: $30,000.00
  Final balance: $206.75
  Net gain/loss: $-29,793.25 (-99.3%)
  Coin flips: 23 heads, 28 tails</code></pre>
</div>
</div>
<p>In this single simulation path, the account balance starts at $30,000 and fluctuates significantly over the 51-year period (from age 24 to age 75) where the balance evolves through a series of coin flips, where each heads increases the balance by 50% and each tails decreases it by 40%.</p>
<p>Looking at this particular run, the outcome is <strong>catastrophic</strong>: despite starting with a $30,000 investment and a positive expected value per flip, this simulation ends with approximately $584—a loss of over <strong>98%</strong> of the initial investment. The volatility is extreme—each flip has substantial impact on the account value. Even with a positive expected value per flip, the compounded nature of these fluctuations means that a few consecutive tails can dramatically reduce the balance. Once the balance drops significantly, even heads become less effective at recovery because they’re multiplying a smaller base value.</p>
<p><strong>Am I happy with this outcome? I am not.</strong> This single simulation reveals the risk: despite the positive expected value calculated in Question 1, there’s a significant chance of ending with less than the original $30,000 investment—in this case, nearly losing everything. The dramatic downward trajectory shown in the plot highlights why expected value alone is insufficient for making this decision. This outcome demonstrates that what matters in the long run isn’t just the expected value, but also the distribution of outcomes and the risk of severe losses.</p>
</section>
<section id="simulations-distribution-of-final-balances" class="level3">
<h3 class="anchored" data-anchor-id="simulations-distribution-of-final-balances">3) 100 Simulations: Distribution of Final Balances</h3>
<div id="cell-q3-dist-100-py" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="q3-dist-100-py" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/q3-dist-100-py-output-1.png" width="758" height="565" class="figure-img"></p>
<figcaption>Distribution of final balances across 100 simulations</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Distribution Statistics (100 simulations):
  Mean final balance: $268,905.14
  Median final balance: $3,230.54
  Minimum final balance: $0.34
  Maximum final balance: $12,323,535.71

Distribution characteristics:
  The mean is 83.2x larger than the median, indicating extreme right-skewness
  Most outcomes cluster at very low values, with a few extreme outliers</code></pre>
</div>
</div>
<p>Running 100 simulations reveals a highly skewed distribution of final account balances. The histogram above shows that while the mean final balance is substantial at approximately $268,905 (due to a few extremely large outcomes), the median is only $3,231—much smaller than the mean. This difference highlights the extreme skewness: most simulations end with final balances well below the initial $30,000 investment, while a few paths create massive values.</p>
<p><strong>What is the probability of outcomes that you’d be happy with after having invested $30,000?</strong></p>
<p>Looking at the distribution, it’s immediately apparent that most outcomes fall well below the initial $30,000 investment (marked by the red dashed line). The vast majority of simulations result in final balances that are far lower than the starting investment, with many ending near zero. Most successful outcomes (those that exceed the initial investment) cluster just above $30,000, suggesting that even when you do beat the initial investment, gains are typically modest—far from the massive outliers that inflate the mean.</p>
<ul>
<li><p><strong>The reality</strong>: Despite the positive expected value per flip calculated in Question 1, most simulations end with devastating losses. The mean being dramatically higher than the median indicates that average performance is heavily inflated by rare but extreme positive outcomes.</p></li>
<li><p><strong>Visual evidence</strong>: The histogram clearly shows that outcomes above the initial investment line are relatively rare compared to the large mass of outcomes clustered at very low values.</p></li>
</ul>
</section>
<section id="probability-balance-30000-at-age-75-original-game" class="level3">
<h3 class="anchored" data-anchor-id="probability-balance-30000-at-age-75-original-game">4) Probability Balance &gt; $30,000 at Age 75 (Original Game)</h3>
<div id="q4-prob-original-py" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>Probability Estimate: P(Final Balance &gt; $30,000) = 0.210

Interpretation:
  Out of 100 simulations, 21 resulted in a final balance above $30,000
  This represents 21.0% of all possible outcomes

Practical Meaning:
  There is approximately a 21.0% chance that you will end up with more
  than your initial $30,000 investment after 51 years of playing this game.
  Conversely, there is a 79.0% chance of losing money or breaking even.</code></pre>
</div>
</div>
<p>Based on the 100 simulations of the original game, the probability that your final account balance exceeds $30,000 at age 75 is approximately <strong>0.210 (21.0%)</strong>. This means that in only 21 out of 100 simulated paths, the final balance was greater than the initial investment.</p>
<p><strong>Practical interpretation</strong>: Despite the positive expected value per flip calculated in Question 1, there is only a <strong>21% chance</strong> of ending up with more than your initial $30,000 investment after 51 years. This stark reality highlights the disconnect between expected value and actual outcomes: while the game has a positive expected return per flip, the long-term compounding of volatility results in most realizations (79%) ending with losses. This low probability of success, combined with the potential for near-total loss (as seen in Question 2), makes this investment strategy highly risky and generally unfavorable despite its theoretical appeal.</p>
</section>
<section id="modified-strategy-bet-25-each-round" class="level3">
<h3 class="anchored" data-anchor-id="modified-strategy-bet-25-each-round">5) Modified Strategy (Bet 25% Each Round)</h3>
<p>Instead of having the full balance at risk with each coin flip, assume only 25% of your balance is gambled each year. Compare this to the original game. Which is riskier? Which has better upside?</p>
<div id="cell-q5-modified-50pct-py" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="q5-modified-50pct-py" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/q5-modified-50pct-py-output-1.png" width="1527" height="566" class="figure-img"></p>
<figcaption>Comparison of original and modified strategies</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Comparison of Strategies:

Original Strategy (100% at risk each flip):
  Mean final balance: $268,905.14
  Median final balance: $3,230.54
  P(final &gt; $30,000): 0.210 (21.0%)
  Min: $0.34, Max: $12,323,535.71

Modified Strategy (25% at risk each flip):
  Mean final balance: $60,241.10
  Median final balance: $46,041.51
  P(final &gt; $30,000): 0.590 (59.0%)
  Min: $4,943.67, Max: $343,035.99

Comparison:
  Difference in P(final &gt; $30,000): +0.380 (+38.0 percentage points)
  Ratio of means (Modified/Original): 0.224
  Ratio of medians (Modified/Original): 14.252</code></pre>
</div>
</div>
<p>Comparing the two strategies reveals fundamental differences in risk and return profiles. The <strong>modified strategy</strong> (betting only 25% of the balance each year) significantly reduces volatility compared to the original game where the entire balance is at risk.</p>
<p><strong>Which is riskier?</strong> The <strong>original strategy is far riskier</strong>. In the modified strategy, only 25% of the balance is at risk each flip. When heads occurs, the outcome is 0.75 + 0.25×1.5 = 1.125×current balance (12.5% gain). When tails occurs, the outcome is 0.75 + 0.25×0.6 = 0.90×current balance (10% loss). This reduced volatility creates much less extreme outcomes compared to the original game’s 50% gain or 40% loss on the entire balance. The original game shows a highly skewed distribution with many near-zero outcomes, while the modified strategy creates a much tighter, more centered distribution around the mean. The lower volatility means the modified strategy has a significantly higher probability of ending above the initial investment.</p>
<p><strong>Which has better upside?</strong> The <strong>original strategy has better upside potential</strong>—its maximum outcome far exceeds that of the modified strategy. However, this upside comes at a severe cost: most outcomes are devastating losses. Or to summarize: the original strategy has more risk and more reward.</p>
</section>
<section id="briefly-explain-your-findings-from-the-previous-step-in-light-of-a-concept-known-as-the-kelly-criterion" class="level3">
<h3 class="anchored" data-anchor-id="briefly-explain-your-findings-from-the-previous-step-in-light-of-a-concept-known-as-the-kelly-criterion">6) Briefly Explain Your Findings From The Previous Step in Light of A Concept Known as the “Kelly Criterion”</h3>
<p>The <strong>Kelly Criterion</strong> is a formula that determines the optimal fraction of capital to bet in order to maximize the long-term growth rate of wealth. For a binary bet where you have probability <span class="math inline">\(p\)</span> of winning with payoff <span class="math inline">\(b\)</span> (as a fraction), and probability <span class="math inline">\(q = 1-p\)</span> of losing with loss <span class="math inline">\(a\)</span> (as a fraction), the optimal Kelly fraction is:</p>
<p><span class="math display">\[f^* = \frac{p \cdot b - q \cdot a}{b \cdot a}\]</span></p>
<p><strong>Applying the Kelly Criterion to our investment game:</strong></p>
<p>In the original game: - Probability of winning (heads): <span class="math inline">\(p = 0.5\)</span> - Gain on win: <span class="math inline">\(b = 0.5\)</span> (50% gain) - Probability of losing (tails): <span class="math inline">\(q = 0.5\)</span> - Loss on lose: <span class="math inline">\(a = 0.4\)</span> (40% loss)</p>
<p>The Kelly optimal fraction is: <span class="math display">\[f^* = \frac{0.5 \times 0.5 - 0.5 \times 0.4}{0.5 \times 0.4} = \frac{0.25 - 0.20}{0.20} = \frac{0.05}{0.20} = 0.25 = 25\%\]</span></p>
<p><strong>How does this relate to the modified strategy?</strong></p>
<p>The modified strategy in Question 5 bets exactly <strong>25% of the balance</strong> each round—precisely the Kelly optimal fraction. The Kelly Criterion tells us that betting 25% of capital each round maximizes the long-term logarithmic growth rate, which explains why the modified strategy performs significantly better than the original game.</p>
<p><strong>Key insights:</strong></p>
<ol type="1">
<li><p><strong>The original strategy violates the Kelly Criterion</strong> by betting 100% of capital, which leads to overbetting. This creates extreme volatility and increases the probability of ruin, as we saw in Questions 2-4.</p></li>
<li><p><strong>The modified strategy follows the Kelly Criterion</strong> by betting 25%, which:</p>
<ul>
<li>Reduces volatility and risk of ruin</li>
<li>Increases the probability of positive returns (higher P(final &gt; $30,000))</li>
<li>Maximizes long-term growth rate</li>
<li>Creates a more stable, less skewed distribution of outcomes</li>
</ul></li>
<li><p><strong>The Kelly Criterion explains the counter-intuitive result</strong>: Despite both strategies having the same expected value per flip, the 25% betting strategy dramatically outperforms the 100% strategy because it optimizes for long-term growth rather than short-term expected value. This demonstrates why expected value alone is insufficient for investment decisions—the fraction of capital at risk matters critically.</p></li>
</ol>
<p>The findings from Question 5 perfectly align with Kelly’s mathematical framework: by reducing the bet size from 100% to the optimal 25%, the modified strategy transforms a high-risk, low-probability-of-success game into a more favorable investment with significantly better risk-adjusted returns.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>